def displayWithdrawals(z):
    print("\n------------------------------------------\n")
    print("Last Withdrawal:\n")
    print(z[0])
    print("\n------------------------------------------\n")
    print("\nSecond Last Withdrawal:\n")
    print(z[1])
    print("\n------------------------------------------\n")
    print("\nThird Last Withdrawal:\n")
    print(z[2])
    print("\n------------------------------------------\n")
